# Generated by Django 5.1.3 on 2024-11-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabom", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(fields=("user", "article"), name="UIX_user_id_article_id"),
        ),
    ]
