# Generated by Django 5.1.3 on 2024-11-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabom", "0002_like_uix_user_id_article_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
